/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//ferdiiiiiii
package Fom;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
//import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dwife
 */
public class Data_item1 extends javax.swing.JFrame {

    
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    Connection conn = Config.koneksi1.KoneksiDB();
    /**
     * Creates new form Data_item1
     */
    public Data_item1() {
        initComponents();
        showdata();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        txt_Harga = new javax.swing.JTextField();
        cmb_Kategori = new javax.swing.JComboBox<>();
        Btn_Hapus = new javax.swing.JButton();
        Btn_Reset = new javax.swing.JButton();
        Btn_Simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Item = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Data item");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Harga");

        txt_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HargaActionPerformed(evt);
            }
        });
        txt_Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_HargaKeyReleased(evt);
            }
        });

        cmb_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIdak ada", " Makanan", " MInuman ", "Coffee" }));

        Btn_Hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Hapus.setText("Hapus");
        Btn_Hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });

        Btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Reset.setText("Reset");
        Btn_Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        Btn_Simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Simpan.setText("Simpan");
        Btn_Simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(Btn_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(Btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_Kategori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Hapus)
                    .addComponent(Btn_Reset)
                    .addComponent(Btn_Simpan))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Item");

        Tbl_Item.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tbl_Item.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tbl_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama item", "Kategori", "Harga"
            }
        ));
        Tbl_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Item);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Kembali ");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void FormatRupiah() {
         if(!txt_Harga.getText().equals("")){
         String Replace=txt_Harga.getText().replaceAll("[^j\\d]", "");
         double FormatRp=Double.parseDouble(Replace);
         DecimalFormat dcf= new DecimalFormat("#,###,###");
         txt_Harga.setText(dcf.format(FormatRp));
         
         }

     }
     
     private String replaceHarga(String harga) {
   
    String hasil = harga.replaceAll("[^\\d]", "");
    if (hasil.isEmpty()) {
        return "0";
    }
    
    return hasil;
}
     
     
    private void txt_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HargaActionPerformed

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        // TODO add your handling code here:
        if (txt_Nama.getText().equals("") || txt_Harga.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Data Tidak Lengkap!", "Validasi", JOptionPane.WARNING_MESSAGE);
           return;
        }
        
           try {
             st=conn.createStatement();
              if(Btn_Simpan.getText()=="Simpan"){
                   String find= "SELECT * FROM tbl_dataitem WHERE nama_item='"+ txt_Nama.getText() +" ' ";
                   rs=st.executeQuery(find);
                   if(rs.next()){
               JOptionPane.showMessageDialog(null,"Data sudah ada! Masukan menu lain", "Validasi", JOptionPane.WARNING_MESSAGE);
              }else{
                   String nama = txt_Nama.getText();
                   String kategori = cmb_Kategori.getItemAt(cmb_Kategori.getSelectedIndex());
                   String harga = txt_Harga.getText();
                   String replaceHarga = replaceHarga(harga);
                   
                   String sql= "INSERT INTO tbl_dataitem (nama_item,Kategori,Harga) VALUES (?,?,?)";
                   ps=conn.prepareStatement(sql);
                   ps.setString(1, nama);
                   ps.setString(2, kategori);
                   ps.setString(3, replaceHarga);
                 
               
                   ps.executeUpdate();
                   JOptionPane.showMessageDialog(null,"Data Berhasil di Simpan", "Input Data", JOptionPane.INFORMATION_MESSAGE);
              
               showdata();
               reset();
               }
            }else{
                  
               int selecttedrow=Tbl_Item.getSelectedRow();
               String No=Tbl_Item.getValueAt(selecttedrow, 0).toString();
               String nama = txt_Nama.getText();
               String kategori = cmb_Kategori.getItemAt(cmb_Kategori.getSelectedIndex());
               String harga = txt_Harga.getText();               
               String replaceHarga = replaceHarga(harga);
               
               String sql= "UPDATE tbl_dataitem SET nama_item=?, kategori=?, harga=? WHERE No=?";
               ps=conn.prepareStatement(sql);
               ps.setString(1, nama);
               ps.setString(2, kategori);
               ps.setString(3, replaceHarga);
               ps.setString(4, No);
               
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null,"Data Berhasil di Update", "Input Data", JOptionPane.INFORMATION_MESSAGE);
              
               showdata();
               reset();
                  
                  
              }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Tbl_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ItemMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel)Tbl_Item.getModel();
          int selecttedrow=Tbl_Item.getSelectedRow();

          txt_Nama.setText(model.getValueAt(selecttedrow, 1).toString());
           String colKat=model.getValueAt(selecttedrow, 2).toString();
              for(int i =0;i<cmb_Kategori.getItemCount();i++){ 
                 if(cmb_Kategori.getItemAt(i).toString().equalsIgnoreCase(colKat)){
                    cmb_Kategori.setSelectedIndex(i);
         }
                 
      }
                txt_Harga.setText(model.getValueAt(selecttedrow, 3).toString());
                Btn_Simpan.setText("Update");
                FormatRupiah();
          
    }//GEN-LAST:event_Tbl_ItemMouseClicked

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_Btn_ResetActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        // TODO add your handling code here:
          try {
            if(txt_Nama.getText().equals("")||txt_Nama.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus","Validasi",JOptionPane.INFORMATION_MESSAGE);
            }else{
                int konfirmasi=JOptionPane.showConfirmDialog(null, "Anda ingin menghapus data, ingin melanjutkan ?", "Hapus Data",JOptionPane.YES_NO_OPTION);
                if(konfirmasi==0){
                    int selecttedrow=Tbl_Item.getSelectedRow();
                    String No=Tbl_Item.getValueAt(selecttedrow, 0).toString();
                    String sql="DELETE FROM tbl_dataitem WHERE No=?";
                    ps=conn.prepareStatement(sql);
                    ps.setString(1, No);
                    ps.executeUpdate();
                    showdata();
                    reset();
                    
                }else{
                   reset();  
                }
            }
        } catch (Exception e) {
         
        }
    }//GEN-LAST:event_Btn_HapusActionPerformed

    private void txt_HargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HargaKeyReleased
        // TODO add your handling code here:
         FormatRupiah();
    }//GEN-LAST:event_txt_HargaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int input = JOptionPane.showConfirmDialog(null, "apakah kamu ingin kembali ke beranda ?",
                "konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(input == 0){
         Beranda lv = new Beranda();
         lv.setLocationRelativeTo(null);
         lv.setVisible(true);
         this.setVisible(false);   // TODO add your handling code here:
    }                         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_item1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_item1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Hapus;
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JTable Tbl_Item;
    private javax.swing.JComboBox<String> cmb_Kategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Nama;
    // End of variables declaration//GEN-END:variables

    private void showdata() {
    DefaultTableModel model = (DefaultTableModel)Tbl_Item.getModel();
    model.setRowCount(0);
    try {
        String sql = "SELECT * FROM tbl_dataitem";
        ps=conn.prepareStatement(sql);
        rs=ps.executeQuery(sql);
        while(rs.next()){  
            int no=rs.getInt("No");
            String nama=rs.getString("nama_item");
            String Kategori=rs.getString("Kategori");
            // Format harga dengan DecimalFormat dan titik sebagai pemisah
            double hargaDb = Double.parseDouble(rs.getString("harga"));
            DecimalFormat df = new DecimalFormat("#,###");
            df.setDecimalFormatSymbols(new DecimalFormatSymbols(new Locale("id")));
            String harga = df.format(hargaDb);
            
            Object[] Rowdata={no,nama,Kategori,harga};
            model.addRow(Rowdata);
        }
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    }

    private void reset() {
       txt_Nama.setText("");
       cmb_Kategori.setSelectedIndex(0);
       txt_Harga.setText("");
       Btn_Simpan.setText("Simpan");
    }
}